### ISSUE TITLE
制御回路の仕様の決定

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/2021IntelligentRobot_circuit#1]
制御回路の要求仕様をこちらに書いてください．
（ただし，全てを採用できるわけではありませんが．．．）

**Comment by yasuohayashibara** [comment]
要求仕様

- ROS (melodic)
- カメラなどのUSB機器の利用
- モータを4つまで駆動可能
- サーボモータを6つまで駆動可能
- PSDセンサなどA/Dのチャンネルを6つ
- ロータリエンコーダのカウンタ2つ
- ステッピングモータを２つまで駆動可

**Comment by MibuchiYuta** [comment]
こちらは制御回路と表記されていますが、電源回路にこちらで議論しますか？

**Comment by yasuohayashibara** [comment]
確かに電源の仕様も必要ですね．
簡単に作るためには以下の組み合わせになりそうな気がします．

- USBモバイルバッテリ
- モータ用電源(3V~12V)

**Comment by yasuohayashibara** [comment]
システム構成を図示してみました．
あくまでも理想的な構成なので，Arduinoの仕様を見ながら機能を調整していきます．

![image](https://user-images.githubusercontent.com/5755200/117556823-fa484780-b0a7-11eb-876d-aeeb25ee468d.png)

**Comment by yasuohayashibara** [comment]
仕様（案）を決定したので，issueを閉じます．
